# Generated by Django 4.2 on 2024-09-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_file_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('AUD', 'Audio'), ('TXT', 'Text'), ('OTH', 'Other')], default='TXT', max_length=5, verbose_name='file type'),
        ),
    ]
